#!/usr/bin/python


# Make a prediction with coefficients
def predict(row, coefficients):
    yhat = coefficients[0]
    row_len = len(row)
    for i in range(row_len-1):
        yhat += row[i] * coefficients[i+1]

    return yhat

def predict_test():
    dataset = [[1, 1], [2, 3], [4, 3], [3, 2], [5, 5]]
    coef = [0.4, 0.8]
    for row in dataset:
        yhat = predict(row, coef)
        print("Expected=%.3f, Predicted=%.3f" % (row[-1], yhat))


def main():
    predict_test()

if __name__ == '__main__':
    main()